name: Run e2e tests

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run e2e tests
        run: docker compose -f docker-compose.ci.yaml --env-file example.env -p ci up --build --exit-code-from api
